Server:
  RunMode: debug
  HttpPort: 8000
  ReatTimeOut: 60
  WriteTimeOut: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: myblog
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
